version: '3.8'

services:
  # Node app
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nodejs
    container_name: pizi-cms-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
